apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-deployment
  labels:
    app: basket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket
  template:
    metadata:
      labels:
        app: basket
    spec:
      containers:
        - name: basket
          image: basketapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CacheSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: basket-configmap
                    key: cache_setting
            - name: GrpcSettings__DiscountUrl
              valueFrom:
                  configMapKeyRef:
                    name: basket-configmap
                    key: grpc_setting      
            - name: EventBusSettings__HostAddress
              valueFrom:
                  configMapKeyRef:
                    name: basket-configmap
                    key: event_bus_setting                                    
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: basket-service
spec:
  type: NodePort
  selector:
    app: basket
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 32002