apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-mongo-deployment
  labels:
    app: catalog-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-mongodb
  template:
    metadata:
      labels:
        app: catalog-mongodb
    spec:
      containers:
        - name: catalog-mongodb
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: catalog-mongo-secret
                  key: mongo-root-username                  
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-mongo-secret
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: catalog-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017