version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "20717:27017"
    volumes:
      - mongo_data:/data/db
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSetting:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "8000:80"
    depends_on:
      - catalogdb

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings:ConnectionString=basketdb:6379
    ports:
      - "8001:80"
    depends_on:
      - basketdb
